-- MySQL Script generated by MySQL Workbench
-- Sun Jun 18 16:29:48 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema todolist
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `todolist` ;

-- -----------------------------------------------------
-- Schema todolist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todolist` DEFAULT CHARACTER SET utf8 ;
USE `todolist` ;

-- -----------------------------------------------------
-- Table `todolist`.`userinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todolist`.`userinfo` ;

CREATE TABLE IF NOT EXISTS `todolist`.`userinfo` (
  `user_no` INT(11) NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(30) NOT NULL,
  `password` VARCHAR(65) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `job` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`user_no`),
  UNIQUE INDEX `id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `todolist`.`todo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todolist`.`todo` ;

CREATE TABLE IF NOT EXISTS `todolist`.`todo` (
  `no` INT(11) NOT NULL AUTO_INCREMENT,
  `userinfo_no` INT(11) NOT NULL,
  `category` VARCHAR(30) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `plan_time` DATETIME NOT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `todo_status` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `userinfo_no` (`userinfo_no` ASC),
  CONSTRAINT `todo_ibfk_1`
    FOREIGN KEY (`userinfo_no`)
    REFERENCES `todolist`.`userinfo` (`user_no`))
ENGINE = InnoDB
AUTO_INCREMENT = 96
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
